### PR TITLE
Changing the documentation

### LINKED ISSUE #610: CPANfile → CPANFile in documentation
Since it's got to have the same name as the actual plugin module.

### PR DESCRIPTION
**Pull request by JJ**
To reflect the actual syntax. When accepted, closes #610.

### CODE REVIEW

**Comment by karenetheridge** [comment]
I think this is a duplicate of #606.

**Comment by JJ** [comment]
Right, but this one passes checks, right? Do you want me to take a look at the other one?

**Comment by dboehmer** [comment]
It's actually the same. The test log from my test looks like a random test failure to me. I feel fine whichever PR is accepted:)

**Comment by rjbs** [comment]
Thanks, applied!

**Pull request closed without merging**
