### PR TITLE
Fix some problems when skipping tests under Win32

### PR DESCRIPTION
**Pull request by klaus03**
This fixes some test failures under Win32

### CODE REVIEW

**Comment by klaus03** [comment]
I just realized that the original TODO should really be a SKIP, hence my second commit...

**Comment by dolmen** [comment]
It seems to be a duplicate of #540 and it has been fixed in the `dev-v6` branch.

**Comment by karenetheridge** [comment]
dev-v6 is now back in master so this should all be good now.

**Comment by rjbs** [comment]
Closing this on the theory that it's fixed by #540

**Pull request closed without merging**
