### PR TITLE
document use of Encoding to avoid problems with AutoPrereqs

### PR DESCRIPTION
**Pull request by dagolden**
Inspired by this blog post:
[Non-obvious fix to a dzil problem](http://goo.gl/rsFQXd)

### CODE REVIEW

**Comment by dolmen** [comment]
:+1:

But add a `L<>` link to the Encoding plugin for easy browsing to its documentation.

**Comment by dagolden** [comment]
@dolmen, done, squashed and pushed

**Comment by rjbs** [comment]
Thanks, I saw the blog post and had the same idea!

**Comment by rjbs** [comment]
i was thinking I'd like to go even further and provide a pointer in the error messages.  I'll look at doing that, too.  Meanwhile: Thanks, applied!

**Comment by jmarca** [comment]
So succinct!  Awesome 9 lines of explanation encapsulates exactly what I was getting at in my meandering blog post.

**Pull request closed without merging**
