### PR TITLE
disregard PAUSE credentials set via dist.ini

### PR DESCRIPTION
**Pull request by karenetheridge**
as discussed on #toolchain.

### CODE REVIEW

**Comment by rjbs** [comment]
I don't recall this conversation.  Got a summary or a timestamp when I can go look at logs?

**Comment by karenetheridge** [comment]
Sorry, I didn't mean to imply that you were involved (nor me, actually!)

The relevant bits that made me look at this code were at 2015-05-29, from 02:48 to 03:28 EDT.

**Comment by rjbs** [comment]
Bonus points for translating the time zone to my language.

**Comment by rjbs** [comment]
Thanks, applied.  I tweaked it: you can provide the username, still.  If username is set, we now use it when prompting you for a password.  ("what's the password for USERNAME:")

**Pull request closed without merging**
