### PR TITLE
add a debug log line when a Dist::Zilla::File::FromCode sub is run

### PR DESCRIPTION
**Pull request by karenetheridge**

### CODE REVIEW

**Comment by rjbs** [comment]
Thanks, applied!

**Comment by rjbs** [comment]
…and now all the tests fail, because Files don't have log_debug delegated.

…which means you probably didn't run the tests before making this PR?

**Comment by karenetheridge** [comment]
doh!!!

is there any good way of accessing the logging object from a file?

**Comment by rjbs** [comment]
I don't think so.

**Comment by karenetheridge** [comment]
reluctantly withdrawing this PR.  a simple `warn` would be ok, if there was a global DEBUG variable or constant to tap into, but I don't think one exists.

**Pull request closed without merging**
