### PR TITLE
in [AutoPrereqs], add prereqs found in xt/ to develop requires.

### PR DESCRIPTION
**Pull request by karenetheridge**
in [AutoPrereqs], add prereqs found in xt/ to develop requires.

### CODE REVIEW

**Comment by robrwo** [comment]
Hi. What's the status of this?

**Comment by rjbs** [comment]
I disagree with Olivier.  If I have smoke tests, I want to make sure they run (like, say, compile!) before shipping to testers, which I'd do with `dzil test --all`.  I want the author prereqs to include anything needed for that.

Drop down to a single file finder, use that, and I'll merge.

**Comment by dolmen** [comment]
I changed my mind. Any `xt/` code (including `xt/smoke`) should be scanned for `develop` deps.

**Comment by karenetheridge** [comment]
Rebased and the three finders are re-collapsed down to `:ExtraTestFiles`.

**Comment by rjbs** [comment]
Thanks, applied.

**Pull request closed without merging**
