### PR TITLE
add header to cpanfile saying it was generated

### PR DESCRIPTION
**Pull request by preaction**
I keep getting PRs for my cpanfile that I keep in the root of my
distribution. To try to head this off, this commit adds a header to the
generated cpanfile telling users that editing it won't work. This
comment is configurable from the dist.ini file

### CODE REVIEW

**Comment by karenetheridge** [comment]
+1. IMHO all auto-generated files should have a comment header explaining where the code lives that generated it (ideally plugin name plus version).

**Comment by preaction** [comment]
I agree with adding a version, though I couldn't find a `$VERSION` variable to use that would make the tests pass (since, I suspect, they're added automatically during the build process). If there's a way I can make that work, let me know and I can update this PR.

**Comment by karenetheridge** [comment]
I usually do `$VERSION // '<internal>'` for distributions that don't have a version declaration right in the repo.

**Comment by preaction** [comment]
Done, the header now includes the version of the plugin.

**Comment by preaction** [comment]
I've reset my branch to begin from the current master.

**Comment by rjbs** [comment]
Thanks, applied!

**Pull request closed without merging**
