### PR TITLE
do not chdir into the source dir when building

### PR DESCRIPTION
**Pull request by karenetheridge**
I read "we must!" and "but it doesn't work!" and I thought "OH REALLY, what doesn't work?" and it turns out that there are only two things in core that don't prepend root properly. There may be plugins out there that are naughty. Let's find out!

### CODE REVIEW

**Comment by rjbs** [comment]
I want to release this soon.  I want to put this in v7.  Therefore I will try to do v7 in less than three years.

**Comment by karenetheridge** [comment]
rebased to new master, which clears up the junk from the dev/v6 merge that was appearing before.

**Comment by karenetheridge** [comment]
rebased to 6.009.

**Comment by rjbs** [comment]
Thanks, applied locally!

**Pull request closed without merging**
