### PR TITLE
allow version ranges in ; authordep specifications

### PR DESCRIPTION
**Pull request by karenetheridge**
...as discovered in Moose when I tried to add this authordep:

    ;authordep List::MoreUtils             = 0.28, != 0.407

### CODE REVIEW

**Comment by karenetheridge** [comment]
related (but does not block merging this change): https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/issues/215

**Comment by karenetheridge** [comment]
*bump* :)

**Comment by karenetheridge** [comment]
rebased to 5.036

**Comment by rjbs** [comment]
thanks, applied!

**Pull request closed without merging**
